development:
  adapter: postgresql
  encoding: unicode
  database: Tanveer
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: Tanveer
  host: localhost
  pool: 5
  username: postgres
  password: postgres

